// Generated by Cypress Author on 2026-05-30
// VIB LexGPT Test Suite

describe('VIB LexGPT Ask Questions', () => {
  const VIB_LOGIN_URL = 'https://vib-client-dev.hacvntech.com/login';
  const VIB_LEXGPT_URL = 'https://vib-client-dev.hacvntech.com/';
  const TEST_CREDENTIALS = {
    email: 'quynhtrangnguyen26@gmail.com',
    password: 'Admin@123'
  };

  beforeEach(() => {
    cy.session('vib-lexgpt-session', () => {
      // Navigate to login page
      cy.visit(VIB_LOGIN_URL);

      // Fill email input
      cy.get('body div#root form input[type=email]').clear().type(TEST_CREDENTIALS.email);

      // Fill password input
      cy.get('body div#root form input[type=password]').clear().type(TEST_CREDENTIALS.password);

      // Click login button
      cy.get('body div#root form button[type=submit]').click();

      // Wait for redirect to main page
      cy.url().should('include', VIB_LEXGPT_URL);
      cy.get('body div#root main').should('be.visible');
    });
  });

  it('should navigate to LexGPT page', () => {
    cy.visit(VIB_LEXGPT_URL);
    cy.get('body div#root main div.vib-qna-scrollbar').should('be.visible');
  });

  it('should ask a question and send to AI', () => {
    cy.visit(VIB_LEXGPT_URL);

    // Verify textarea is visible
    cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]')
      .should('be.visible')
      .and('be.enabled');

    // Type a test question
    const testQuestion = 'What are my legal rights?';
    cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]')
      .clear()
      .type(testQuestion);

    // Verify text is entered
    cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]')
      .should('have.value', testQuestion);

    // Click send button (within toolbar)
    cy.get('body div#root main div.vib-qna-scrollbar div.items-center.justify-between button.w-10.h-10.rounded-full')
      .should('be.visible')
      .click();

    // Verify question was submitted by checking if textarea is cleared or response appears
    cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]', { timeout: 5000 })
      .should('have.value', '');

    // Wait for AI response to appear (smoke test)
    cy.get('body div#root main div.vib-qna-scrollbar', { timeout: 10000 })
      .should('contain.text', testQuestion)
      .or('contain.text', 'legal');
  });

  it('should allow multiple questions', () => {
    cy.visit(VIB_LEXGPT_URL);

    const questions = [
      'What is contract law?',
      'How do I draft a document?',
      'Tell me about LexGPT'
    ];

    questions.forEach((question, index) => {
      // Type question
      cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]')
        .clear()
        .type(question);

      // Send question
      cy.get('body div#root main div.vib-qna-scrollbar div.items-center.justify-between button.w-10.h-10.rounded-full')
        .click();

      // Verify textarea is cleared
      cy.get('body div#root main div.vib-qna-scrollbar textarea[placeholder="Hãy đặt câu hỏi cho tôi"]', { timeout: 5000 })
        .should('have.value', '');

      // Add delay between questions to allow response to process
      if (index < questions.length - 1) {
        cy.wait(2000);
      }
    });
  });
});
